# Generated by Django 3.1.7 on 2021-04-05 16:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
